name: Publishing
on:
  workflow_dispatch:
  push:
    paths:
      - package.json
    branches:
      - stable
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'XzFirzal/discord-media-player' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install Dependencies
        run: npm ci --no-optional

      - name: Run Build
        run: npm run build

      - name: Publish New Version
        run: |
          npm config set registry https://registry.npmjs.org
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}